title: Jiahao Hu(胡珈豪)'s Homepage
page-top-title: Jiahao Hu (胡珈豪)
top-section-bg-text: Hey Bro! Welcome to my homepage<br />～(∠・ω< )⌒☆.
home-subtitle: Jiahao Hu&ensp;|&ensp;胡珈豪
copyright-text: '&copy; Jiahao Hu 2024-2025. All Rights Reserved.'
